import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter_ai/data/gemini_api.dart';
import 'package:flutter_ai/domain/entity/chat.dart';
import 'package:flutter_ai/theme/constants.dart';
import 'package:flutter_ai/widgets/mark_down_text.dart';
import 'package:flutter_ai/widgets/vector_icon.dart';

class ChatPage extends StatefulWidget {
  const ChatPage({super.key});

  @override
  State<ChatPage> createState() => _ChatPageState();
}

class _ChatPageState extends State<ChatPage> {
  late final GeminiApi _api;
  late final TextEditingController _controller;
  late final ScrollController _scrollController;
  late FocusScopeNode _focusScope;
  final List<Chat> _chats = [];
  bool _isStreaming = false;

  @override
  void initState() {
    super.initState();
    _api = GeminiApiImpl();
    _controller = TextEditingController();
    _scrollController = ScrollController();
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _focusScope = FocusScope.of(context);
  }

  @override
  void dispose() {
    _controller.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  void _scrollToBottom() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (_scrollController.hasClients) {
        _scrollController.animateTo(
          _scrollController.position.maxScrollExtent,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    });
  }

  void _onTapSend() {
    final text = _controller.text.trim();
    if (text.isEmpty || _isStreaming) return;
    _controller.clear();
    _focusScope.unfocus();

    // Pass the current chats as history (before adding the new message)
    final stream = _api.generateContent(_chats.toList(), text);

    setState(() {
      _chats.add(Chat.user(text));
      _chats.add(Chat.ai(stream: stream));
      _isStreaming = true;
    });

    _scrollToBottom();
  }

  void _onStreamDone() {
    if (_isStreaming) {
      setState(() {
        _isStreaming = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          onPressed: () {},
          icon: const VectorIcon(icon: AppIcons.menu),
        ),
        title: const Text('Gyani AI'),
        actions: [
          IconButton(onPressed: () {}, icon: const Icon(Icons.more_vert)),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: ListView.builder(
              controller: _scrollController,
              padding: const EdgeInsets.only(
                left: AppSpacing.m,
                right: AppSpacing.m,
                top: AppSpacing.s,
                bottom: AppSpacing.xxxl,
              ),
              itemCount: _chats.length,
              itemBuilder: (context, index) {
                final message = _chats[index];

                if (message.isUser) {
                  return ChatBubble(text: message.text);
                }

                // AI message — use StreamBuilder if stream is available
                // and text is still empty (stream hasn't completed yet)
                if (message.stream != null) {
                  return _AiStreamingMessage(
                    message: message,
                    onStreamDone: _onStreamDone,
                    onData: _scrollToBottom,
                  );
                }

                // AI message with completed text
                return index == _chats.length - 1
                    ? Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          MarkDownText(text: message.text),
                          AppGaps.hM,
                          Center(
                            child: Text(
                              'Generated by Gemini-2.5-flash model.',
                              style: theme.textTheme.bodySmall,
                            ),
                          ),
                        ],
                      )
                    : MarkDownText(text: message.text);
              },
            ),
          ),
          // Prompt Edition Panel
          SafeArea(
            top: false,
            child: PromptEditionPanel(
              controller: _controller,
              onTapSend: _onTapSend,
              isSendEnabled: !_isStreaming,
            ),
          ),
        ],
      ),
    );
  }
}

/// Displays an AI message that is currently streaming.
class _AiStreamingMessage extends StatelessWidget {
  const _AiStreamingMessage({
    required this.message,
    required this.onStreamDone,
    required this.onData,
  });

  final Chat message;
  final VoidCallback onStreamDone;
  final VoidCallback onData;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return StreamBuilder<String>(
      stream: message.stream,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Padding(
            padding: const EdgeInsets.symmetric(vertical: AppSpacing.m),
            child: Row(
              children: [
                SizedBox(
                  width: AppSpacing.m,
                  height: AppSpacing.m,
                  child: CircularProgressIndicator(
                    strokeWidth: 2,
                    color: theme.colorScheme.primary,
                  ),
                ),
                AppGaps.wS,
                Text(
                  'Thinking...',
                  style: theme.textTheme.bodyMedium?.copyWith(
                    color: theme.colorScheme.onSurfaceVariant,
                  ),
                ),
              ],
            ),
          );
        }

        if (snapshot.hasError) {
          SchedulerBinding.instance.addPostFrameCallback((_) => onStreamDone());
          return Padding(
            padding: const EdgeInsets.symmetric(vertical: AppSpacing.s),
            child: Text(
              'Error: ${snapshot.error}',
              style: theme.textTheme.bodyMedium?.copyWith(
                color: theme.colorScheme.error,
              ),
            ),
          );
        }

        // Update the message text as data comes in
        if (snapshot.hasData) {
          // message.text = snapshot.data!;
          SchedulerBinding.instance.addPostFrameCallback((_) => onData());
        }

        // Stream completed — persist the final text
        if (snapshot.connectionState == ConnectionState.done) {
          message.setText(snapshot.data!);
          SchedulerBinding.instance.addPostFrameCallback((_) => onStreamDone());
        }

        if (message.text.isEmpty) {
          return const SizedBox.shrink();
        }

        return MarkDownText(text: message.text);
      },
    );
  }
}

class ChatBubble extends StatelessWidget {
  const ChatBubble({super.key, required this.text});

  final String text;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Align(
      alignment: Alignment.centerRight,
      child: Container(
        padding: const EdgeInsets.symmetric(
          horizontal: AppSpacing.l,
          vertical: AppSpacing.m,
        ),
        margin: const EdgeInsets.only(
          bottom: AppSpacing.m,
          top: AppSpacing.m,
          left: AppSpacing.xxxl,
        ),
        decoration: BoxDecoration(
          color: theme.colorScheme.primaryContainer,
          borderRadius: const BorderRadius.only(
            topLeft: AppRadius.xl,
            topRight: AppRadius.xs,
            bottomLeft: AppRadius.xl,
            bottomRight: AppRadius.xl,
          ),
        ),
        child: Text(text, style: theme.textTheme.bodyLarge),
      ),
    );
  }
}

class PromptEditionPanel extends StatelessWidget {
  PromptEditionPanel({
    super.key,
    required this.controller,
    required this.onTapSend,
    this.isSendEnabled = true,
  }) : _isEditing = ValueNotifier<bool>(false);

  final TextEditingController controller;
  final VoidCallback onTapSend;
  final bool isSendEnabled;
  final ValueNotifier<bool> _isEditing;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Container(
      padding: const EdgeInsets.only(
        left: AppSpacing.m,
        right: AppSpacing.m,
        top: AppSpacing.s,
        bottom: AppSpacing.m,
      ),
      decoration: BoxDecoration(
        color: theme.colorScheme.surfaceContainer,
        border: Border(
          top: BorderSide(color: theme.colorScheme.outlineVariant, width: 1),
        ),
        borderRadius: const BorderRadius.only(
          topLeft: AppRadius.xl,
          topRight: AppRadius.xl,
        ),
      ),
      child: Column(
        children: [
          TextField(
            controller: controller,
            onChanged: (value) => _isEditing.value = value.isNotEmpty,
            maxLines: 5,
            minLines: 1,
            style: theme.textTheme.bodyLarge,
            decoration: const InputDecoration(hintText: 'Ask me anything'),
          ),
          Row(
            children: [
              IconButton(
                onPressed: () {},
                icon: const VectorIcon(icon: AppIcons.cross),
              ),
              AppGaps.wS,
              IconButton(
                onPressed: () {},
                icon: const VectorIcon(icon: AppIcons.tune),
              ),
              const Spacer(),
              IconButton(
                onPressed: () {},
                icon: const VectorIcon(icon: AppIcons.mic),
                style: IconButton.styleFrom(
                  fixedSize: const Size.square(48),
                  side: BorderSide(
                    width: 1,
                    color: theme.colorScheme.outlineVariant,
                  ),
                ),
              ),
              AppGaps.wS,
              ValueListenableBuilder(
                valueListenable: _isEditing,
                builder: (context, value, child) {
                  return AnimatedSwitcher(
                    duration: const Duration(milliseconds: 300),
                    switchInCurve: Curves.easeIn,
                    switchOutCurve: Curves.easeOut,
                    child: value
                        ? IconButton(
                            key: const ValueKey('send'),
                            onPressed: isSendEnabled ? onTapSend : null,
                            icon: const VectorIcon(icon: AppIcons.send),
                            style: IconButton.styleFrom(
                              fixedSize: const Size.square(48),
                              backgroundColor:
                                  theme.colorScheme.primaryContainer,
                            ),
                          )
                        : IconButton(
                            key: const ValueKey('aiEdit'),
                            onPressed: () {},
                            icon: const VectorIcon(icon: AppIcons.aiEdit),
                            style: IconButton.styleFrom(
                              fixedSize: const Size.square(48),
                              backgroundColor:
                                  theme.colorScheme.primaryContainer,
                            ),
                          ),
                  );
                },
              ),
            ],
          ),
        ],
      ),
    );
  }
}
